### ISSUE TITLE
kvmemn2n training time - help

### ISSUE THREAD

**Issue by chanm12** [NervanaSystems/nlp-architect#10]
#### Target objective:
I am running train_kvmemn2n.py on MacBook Pro with epoc=2000. It is completing at the rate of about 10 epochs per day, and at this rate I estimate 20 days to complete the training. Any ideas on how to speed it up? Does it need to train for 2000 epochs to create the model? Help appreciated. Is there a pre-built model I can leverage and add to?
#### Steps to objective:
- [ ]
- [ ]

**Comment by bethke** [comment]
The model does take quite some time to complete, but you should have a pretty good model after around epoc=200. The model will save incrementally, and you can load it from memory so it is easy to stop the training cycle once you see performance that you like. To speed it up you could try using a larger batch size. Definitely make sure that the --mem_mode is kb, as the text mode is much slower. Hope that helps!

**Comment by peteriz** [comment]
@chanm12 was this ^^ answer helpful? 
I will close the issue if you have no further questions.

**Comment by chanm12** [comment]
Yes, you can close this issue. Thanks for the response.
