### ISSUE TITLE
bug: [CLS] token receives wrong token_id

### ISSUE THREAD

**Issue by ofirzaf** [NervanaSystems/nlp-architect#100]
According to BERT paper the token type of `[CLS]` token should be `0`, however in sequence classification model it receives token type `1`

https://github.com/NervanaSystems/nlp-architect/blob/2f2eae3671b70a0e233ed77f385944f62ed127cf/nlp_architect/models/transformers/sequence_classification.py#L159-L160

**Comment by peteriz** [comment]
I think this was fixed with latest update to `transformers`
