### ISSUE TITLE
question: Does quantization affect only weights, or also activations?

### ISSUE THREAD

**Issue by walmsley** [NervanaSystems/nlp-architect#114]
With your 8-bit quantized GNMT model, I understand that the weights are quantized to 8-bit and then treated as floating point during inference. Does this mean that the 8-bit weights are interacting with float32 activations? Or are the activations also effectively quantized to 8-bit?

**Comment by ofirzaf** [comment]
The weights are quantized to Int8 and saved as Int8 variables.
Before inference the Int8 weights are loaded from the checkpoint and dequantized to FP32.
Inference is done in FP32 and there is no interaction at all with quantized values.

**Comment by walmsley** [comment]
Okay, got it - activations are not ever quantized, neither "dynamically" nor "statically" [(going by these definitions)](https://pytorch.org/docs/stable/quantization.html#quantization-workflows).

However, are the embedding layer weights included in the weight quantization? If so, then I guess the activations are initially influenced by the quantization, because the activations originate from vectors pulled from the embedding layer. Does that sound right?

**Comment by ofirzaf** [comment]
Yes, sounds right
