### ISSUE TITLE
Where to get coref.dict1.tsv?

### ISSUE THREAD

**Issue by anastasia-zhukova** [NervanaSystems/nlp-architect#126]
Hello, 
I am executing examples/cross_doc_coref/cross_doc_coref_sieves.py, and got the following error: 

FileNotFoundError: Referent Dict file not found or not in path:C:\Users\annaz\PycharmProjects\nlp_architect\dataset\coref.dict1.tsv

How could I get this file?

Thank you in advance. 
Best, 
Anastasia

**Comment by AlonEirew** [comment]
Hi Anastasia, 

Sorry for the delay in response, you can download it from:
http://nlp.stanford.edu/pubs/coref-dictionary.zip

Alon.
