### ISSUE TITLE
bug: [AttributeError: 'QuantizedBertLayer' object has no attribute 'is_decoder']

### ISSUE THREAD

**Issue by iamweiweishi** [NervanaSystems/nlp-architect#128]
**Describe the bug**
I am trying to train Quantized BERT use the following code snippet:
nlp-train transformer_glue \
    --task_name mrpc \
    --model_name_or_path bert-base-uncased \
    --model_type quant_bert \
    --learning_rate 2e-5 \
    --output_dir /tmp/mrpc-8bit \
    --evaluate_during_training \
    --data_dir /path/to/MRPC \
    --do_lower_case
And I tried the two install methods in README.
But the AttributeError occured?

**Expected behavior**
Could you pls help me with this?

**Environment setup: **
 - OS (Linux/Ubuntu_64):
 - Python version: 3.7
- Backend: Pytorch 1.3.1

Many thanks.

**Comment by lememta** [comment]
I just came here to report the same bug.

**Comment by ofirzaf** [comment]
Fixed in #129
