### ISSUE TITLE
bug: [BokehDepreciationWarning]

### ISSUE THREAD

**Issue by amygeorge** [NervanaSystems/nlp-architect#142]
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

**To Reproduce**
1. Extract a new lexicon
2. Run "Classify"
3. Attempt to click on Bokeh
4. Nothing shows up

**Expected behavior**
See the example sentence or aspect

**Environment setup: **
 - OS (Linux/Mac OS): Linux Ubuntu 18.04
 - Python version: 3.6
- Backend:

**Additional context**
![bokeh_plot](https://user-images.githubusercontent.com/15726648/75295121-e421d480-57de-11ea-9f34-6823e8254a7a.png)

**Comment by peteriz** [comment]
@danielkorat

**Comment by danielkorat** [comment]
Hi @amygeorge ,
Thanks for noticing, please try rolling back to bokeh version 1.2.0.
