### ISSUE TITLE
bug: [Import typo]

### ISSUE THREAD

**Issue by amygeorge** [NervanaSystems/nlp-architect#143]
**Describe the bug**
In the file /nlp-architect/solutions/absa_solution/sentiment_solution.py line number 42 which is:
from .utils import Anonymiser, _ui_format should be written as from utils import Anonymiser, _ui_format without the period in front of utils.

**Comment by danielkorat** [comment]
Fixed, thanks!
@amygeorge

**Comment by amygeorge** [comment]
Hi, I just pulled from master and the issue is still there.
