### ISSUE TITLE
bug: [Missing file]

### ISSUE THREAD

**Issue by amygeorge** [NervanaSystems/nlp-architect#144]
**Describe the bug**
 The file /nlp-architect/solutions/absa_solution/dropdown.js needs to be copied and pasted in /nlp-architect/examples/absa/solution. In both the gitgub and website versions it's missing when I installed the code and had to manually copy the file to the right destination.

**Comment by danielkorat** [comment]
Thanks @amygeorge 
I fixed the path now, so no need to copy the file.
BTW, you're welcome to check the beta version of ABSA with improved precision and significant speedups (x47 for parsing (!) and x3.5 overall for training). This version is available on the [absa](https://github.com/NervanaSystems/nlp-architect/tree/absa) branch.
