### ISSUE TITLE
question: [Changing out ELMo for Clinical BERT Embeddings]

### ISSUE THREAD

**Issue by amygeorge** [NervanaSystems/nlp-architect#146]
Hi! I'm trying to use ABSA for clinical notes, and I'm wondering if it would be possible to switch out ELMo for BERT - specifically BERT-Base and BioBERT-finetuned models trained on both all clinical notes and only discharge summaries as per [this article.](https://arxiv.org/abs/1904.03323)
How hard do you think it would be if you think it's even possible? Thanks!!

**Comment by danielkorat** [comment]
Hi @amygeorge 
Please see the algorithm description in the documentation, [here](http://nlp_architect.nervanasys.com/sentiment.html). 
Our model only uses Word2Vec embedding (not ELMo) in the final re-ranking phase.
From documentation:
"4. The last step includes applying an MLP based opinion term re-ranking and polarity estimation algorithm. This step is based on using the word embedding similarities between each acquired term and a set of generic opinion terms as features. A pre-trained model is re-ranking provided."

As I see it, this similarity model cannot work directly with contextual word-embeddings, which encode multiple words.
However, you can try to combine BERT with our algorithm by training it to extract aspects for your task, and feeding them as the aspect lexicon.

Best
Daniel

**Comment by amygeorge** [comment]
Thanks @danielkorat 
I was under the impression from this [documentation](http://nlp_architect.nervanasys.com/_modules/nlp_architect/data/cdc_resources/embedding/embed_elmo.html#ElmoEmbedding.get_elmo_avg) that ELMo was being used.
I will look into what I can do by running BERT first and passing them in as aspects.
Thanks for the suggestions!
