### ISSUE TITLE
question: [Inference Displayed]

### ISSUE THREAD

**Issue by amygeorge** [NervanaSystems/nlp-architect#147]
So is the interface only supposed to display aspect opinion pairs extracted from the data instead of all the potential opinion pairs from the bootstrap lexicon? Is this a bug or a feature?

**Comment by danielkorat** [comment]
Hi @amygeorge 
As per the ABSA task definition, the interface displays aspect-opinion pairs extracted from the data.
Generating all potential pairs is interesting, but may result in a very large quantity of pairs, many of which will be incompatible if performed naively (like "friendly"-"pasta").
