### ISSUE TITLE
bug: [tensorflow 1.15 issue when installing]

### ISSUE THREAD

**Issue by amygeorge** [NervanaSystems/nlp-architect#149]
**Describe the bug**
Whenever I try to install nlp-architect from scratch, I always run into an issue with the version of tensorflow.

**To Reproduce**
1. Follow the directions to install from source
2. pip install -e .
3. get error
Could not find a version that satisfies the requirement tensorflow==1.15.2 (from nlp-architect==0.5.3) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15.2 (from nlp-architect==0.5.3)

**Solution:**
https://github.com/RasaHQ/rasa/issues/4782
Make sure pip is upgraded to pip 19 or above

**Environment setup: **
 - OS (Linux/Mac OS):linux
 - Python version:3.6
- Backend:

**Additional context**

**Comment by peteriz** [comment]
Hi @amygeorge, please try installing Tensorflow 1.15.2 again, it should work since its a valid release.

```
❯ pip install tensorflow==
Collecting tensorflow==
  ERROR: Could not find a version that satisfies the requirement tensorflow== (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 1.15.0, 1.15.2, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.2.0rc0, 2.2.0rc1)
```
