### ISSUE TITLE
Problem with downloading pre-trained models

### ISSUE THREAD

**Issue by Plazmius** [NervanaSystems/nlp-architect#15]
#### Description:
Hello everyone. I tried to launch REST server as in following tutorial: [Link](http://nlp_architect.nervanasys.com/service.html). However, in process of starting server some pre-trained models were downloaded, and seems like some model files contain only error. Starting server crashes with KeyError on trying to unpickle model_info.dat in ner_api.py. Contents of model_info.dat after download:
`<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>NLP/NER/model_info.dat</Key><RequestId>7113734D2CFD0F64</RequestId><HostId>L8Szl6PSef3HNZ7nKMF20Ji2xjDfSpxPiAo6CnlBvrOJyffPYxHtMJTf+GWAwuw+mOlLO+vH6uw=</HostId></Error>`
#### Steps to reproduce:
- [x] Clone nlp-architect
- [x] Make environment (`make` in root)
- [x] Launch server (`hug -p 8080 -f server/serve.py`)

**Comment by peteriz** [comment]
Hi @Plazmius, thanks for reporting this error. 
We've fixed the model files and the above should work.
