### ISSUE TITLE
bug: [quant bert config json not available]

### ISSUE THREAD

**Issue by vincentlux** [NervanaSystems/nlp-architect#163]
**Describe the bug**
It appears that https://nlp-architect-data.s3-us-west-2.amazonaws.com/models/transformers/bert-base-uncased.json link from https://github.com/NervanaSystems/nlp-architect/blob/70cb5f3fc1923efeccf98263dd80896bb058f94b/nlp_architect/models/transformers/quantized_bert.py#L59 is dead and a config.json file cannot be loaded properly. May I ask if the link can be updated? Thanks!

**Comment by peteriz** [comment]
Hi @vincentlux. We had an issue on AWS that we've just fixed. 
The config is available now.

**Comment by pbamotra** [comment]
This bug is happening again `OSError: Couldn't reach server at 'https://nlp-architect-data.s3-us-west-2.amazonaws.com/models/transformers/bert-base-uncased.json' to download pretrained model configuration file.`

**Comment by peteriz** [comment]
Please use the recent release from the master branch. We had to update all our links.
Thanks

________________________________
