### ISSUE TITLE
installing and set-expansion data processing error

### ISSUE THREAD

**Issue by PxYu** [NervanaSystems/nlp-architect#17]
Hi, I am trying to install NLP-architect and run [set-expansion](http://nlp_architect.nervanasys.com/term_set_expansion.html) solution. However I met some problems:

1. Trying to run the command given at [set-expansion](http://nlp_architect.nervanasys.com/term_set_expansion.html) on my desktop:

`python -m nlp_architect.solutions.set_expansion.prepare_data.py --corpus TRAINING_CORPUS --marked_corpus MARKED_TRAINING_CORPUS`

I would get the following error:

> /usr/bin/python3: Error while finding module specification for 'nlp_architect.solutions.set_expansion.prepare_data.py' (AttributeError: module 'nlp_architect.solutions.set_expansion.prepare_data' has no attribute '__path__')

what could be the problem here?

2. When I try to run the exact same thing on a server, I got the following error:

> [1]    13988 illegal hardware instruction  python -m nlp_architect.solutions.set_expansion.prepare_data.py --corpus

what could be the problem here? For your information, this is the CPU info about my server:

> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 15
> model           : 6
> model name      : Intel(R) Xeon(TM) CPU 3.00GHz
> stepping        : 4
> microcode       : 0x2
> cpu MHz         : 2992.630
> cache size      : 2048 KB
> physical id     : 0
> siblings        : 2
> core id         : 0
> cpu cores       : 2
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 6
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc pebs bts nopl pni dtes64 monitor ds_cpl vmx est cid cx16 xtpr pdcm lahf_lm tpr_shadow
> bogomips        : 5985.26
> clflush size    : 64
> cache_alignment : 128
> address sizes   : 36 bits physical, 48 bits virtual
> power management:

**Comment by PxYu** [comment]
solved problem 1 by deleting the ".py" in the command
the command should be 

`python -m nlp_architect.solutions.set_expansion.prepare_data --corpus TRAINING_CORPUS --marked_corpus MARKED_TRAINING_CORPUS`

**Comment by peteriz** [comment]
Hi, thanks for letting us know. We'll push a fix soon.

**Comment by peteriz** [comment]
Hi @PxYu, thanks for issue 1, we've fixed our documentation.
Can you provide more details regarding issue 2? we haven't seen this kind of error before.
Thanks

**Comment by PxYu** [comment]
@peteriz It's probably because I was using a server with very old processors. Switching to a relatively new processor solved the problem. From the CPU information I provided earlier, I assume the reason is that the CPU doesn't support SSSE3 instruction set.
