### ISSUE TITLE
Getting ValueError('Length  must be less than 1000') error

### ISSUE THREAD

**Issue by stevesolun** [NervanaSystems/nlp-architect#172]
I am trying to run ABSA with the a CSV and getting this error.
I have sent the file to @danielkorat. It contains 1000 rows and it fails with the above error.

Please advise how can it be solved. Until now 500K reviews (in one file) have been sent and it worked.

**Comment by stevesolun** [comment]
Here is another information about the bug:
`_handler:error handling message Message 'PATCH-DOC' (revision 1) content: {'events': [{'kind': 'ModelChanged', 'model': {'type': 'ColumnDataSource', 'id': '1049'}, 'attr': 'data'`

**Comment by stevesolun** [comment]
It fails on the following phrase (line) of the reviews:

`This app is so amazing I love this app❣️❣️💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟💟❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️❣️💞💞💞💞💞💞💞💞💞💞💞💞💗💗💗💗💞💞💞💗💗💗💞💗💗💗💗💗💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💞💓💓💓💓❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤`

**Comment by danielkorat** [comment]
Hi @stevesolun 
Yes, I debugged it and found this line to be the problem. When I removed it from the CSV everything works.
For security reasons, our library rejects reviews containing more than 1000 characters.
The length of this line is 1102 (because of the emojis).
To solve, please clean your data from emojis (which are not useful for the algorithm anyway).
Daniel

**Comment by stevesolun** [comment]
@danielkorat thanks a lot!
Please advise where can I change this 1000 limit setting?

**Comment by danielkorat** [comment]
Hi @stevesolun 
You need to change the last value in [this](https://github.com/NervanaSystems/nlp-architect/blob/e6b6ba0164c23ddb4dc9c2aff700e0e9e4521ade/nlp_architect/common/core_nlp_doc.py#L66) line
