### ISSUE TITLE
Error: Term file is empty, no terms to re-rank.

### ISSUE THREAD

**Issue by stevesolun** [NervanaSystems/nlp-architect#178]
Using your Docker file I have installed everything and was able to run the solution.
It fails on every file with:

```
Running_SentimentTraining on data...

#Iteration: 1
100%|#########################################################################################################################| 5054/5054 [00:00<00:00, 76319.93it/s]

#Iteration: 2
100%|#########################################################################################################################| 5054/5054 [00:00<00:00, 68837.46it/s]
Aspect lexicon written to /root/nlp-architect/cache/absa/train/lexicons/generated_aspect_lex.csv

Loading feature table...

Loading training data from /root/nlp-architect/cache/absa/train/lexicons/generated_opinion_lex.csv ...
/workspace/nlp-architect/nlp_architect/models/absa/train/rerank_terms.py:148: UserWarning: genfromtxt: Empty input file: "/root/nlp-architect/cache/absa/train/lexicons/generated_opinion_lex.csv"
  table = np.genfromtxt(filename, delimiter=",", skip_header=1, dtype=str)
ERROR:bokeh.server.protocol_handler:error handling message Message 'PATCH-DOC' (revision 1) content: {'events': [{'kind': 'ModelChanged', 'model': {'type': 'ColumnDataSource', 'id': '1049'}, 'attr': 'data', 'new': {'file_contents':
```

**Comment by danielkorat** [comment]
Hi @stevesolun 
From the log you sent looks like it's trying to load training data from the wrong file. 
Please share what steps you took in the UI and which files did you load into the system.

**Comment by stevesolun** [comment]
@danielkorat You can try to do the same with your test file.
My files aren't different from any other - I have an excel, like the one I have sent you privately on FB and the only contents are the column with the reviews.

I suggest that we will make a quick zoom call and I will be happy to show you all the issues. You can record it and fix the bugs.

What do you think?

Everything is working for me but I am not using the latest solution (merge and your fixes) because it didn't work for me. I have changed the repository and now it works within a simple docker.

Let me know what do you think, I think it worth Intel's time.

**Comment by danielkorat** [comment]
Hi @stevesolun 
Since "Extract Lexicons" works for me (tested UI on Ubuntu 16), this might be an OS compatibility issue.
I have no resources to test on other OS right now. Let me know if I can help somehow.
I created a PR which fixes the bug in "Classify" step: [PR-182](https://github.com/NervanaSystems/nlp-architect/pull/182)
It will be merged soon.
