### ISSUE TITLE
NP2vec Tutorial Bug

### ISSUE THREAD

**Issue by tahmidb** [NervanaSystems/nlp-architect#186]
**Describe the bug**
I was following the NP2vec tutorial: https://github.com/NervanaSystems/nlp-architect/blob/master/tutorials/NP2vec/NP2vec_training.ipynb

When I tried to run the import step to get the nlp_architect.solutions module
for using set_expansion, the module never gets found on the import and 
I get a ModuleNotFoundError message.

**To Reproduce**
1. Run ```from nlp_architect.solutions.set_expansion.prepare_data import load_parser, mark_noun_phrases``` in jupyter notebook

**Expected behavior**

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-313a79c068a7> in <module>
      3 
      4 from nlp_architect.models.np2vec import NP2vec
----> 5 from nlp_architect.solutions.set_expansion.prepare_data import load_parser, mark_noun_phrases

ModuleNotFoundError: No module named 'nlp_architect.solutions'
```

**Environment setup: **
 - OS (Linux/Mac OS): Mac OS
 - Python version: 3.6 Conda Environment
- Backend:

**Additional context**
I am running nlp-architect version 0.5.4

**Comment by peteriz** [comment]
Hi @tahmidb, I fixed the tutorial (wrong paths), and it should work as expected.
Thanks!
