### ISSUE TITLE
Terms file is empty, no terms to re-rank

### ISSUE THREAD

**Issue by stevesolun** [NervanaSystems/nlp-architect#189]
Running the following Dockerfile:

Prior running the docker build command please clone the repository and copy the solution dir to nlp_architect folder.
Place the following Dockerfile inside nlp-architect and run it from nlp-architect dir.

```
cd nlp-architect/
docker build -t nlp-architect .
```
```
FROM ubuntu:18.04
LABEL maintainer="Intel AI Lab NLP [Steve's working solution]"

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y bash build-essential ca-certificates python3 python3-pip git vim && \
    rm -rf /var/lib/apt/lists && \
    apt-get clean

RUN python3 -m pip install --no-cache-dir --upgrade pip setuptools

ENV LC_ALL=C.UTF-8

WORKDIR /workspace

COPY . /workspace/nlp-architect/

WORKDIR /workspace/nlp-architect/

RUN pip install -e . && \
    pip install -r nlp_architect/solutions/absa_solution/requirements.txt

RUN python3 -m spacy download en

ENV BOKEH_ALLOW_WS_ORIGIN=[YOUR LOCAL HOST IP (e.g 10.0.0.1)]:5006

WORKDIR /workspace/nlp-architect/nlp_architect/solutions/absa_solution/

CMD ["python3","ui.py"]

EXPOSE 5006
```

Running it with or without mounted dir (with embeddings and rerank models) gives the following error:

`ValueError('Error: Terms file is empty, no terms to re-rank.', )`

It happens on the third iteration.

**Comment by danielkorat** [comment]
Hi @stevesolun 
As per our conversation, this error is caused by wrong CSV format.
Please open a PR for the other str decoding bug you discovered.
Thanks
