### ISSUE TITLE
intent_extraction_demo.ipynb is not working using nlp_architect v0.3.1

### ISSUE THREAD

**Issue by RajeswariPonnuru** [NervanaSystems/nlp-architect#20]
#### Target objective:
Trying to run intent classification demo "intent_extraction_demo.ipynb" using default dataset mentioned in notebook itself. 
#### Steps to objective:
- Intents are not onehot encoded so got below error

“ValueError: Error when checking target: expected intent_classifier_output to have shape (7,) but got array with shape (1,)”
- I have tried in 2 ways, done explicit onehot encoding on my own and tried to import one_hot from v0.2. After importing, intent array is converted to one-hot encoded format. But getting the below error.

Train on 13784 samples, validate on 700 samples
Epoch 1/1
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-20-b58df2dd9efb> in <module>()
      4 # train the model
      5 model.fit([train_x, train_c], [train_i, train_y],batch_size=batch_size,epochs=no_epochs,
----> 6          validation=([test_x, test_c], [test_i, test_y]))
      7 
      8 #model.fit([train_x, train_c], [intent_labels,train_y],batch_size=batch_size,epochs=no_epochs)

~/.local/lib/python3.6/site-packages/nlp_architect/models/intent_extraction.py in fit(self, x, y, epochs, batch_size, callbacks, validation)
     52         self.model.fit(x, y, epochs=epochs, batch_size=batch_size, shuffle=True,
     53                        validation_data=validation,
---> 54                        callbacks=callbacks)
     55 
     56     def predict(self, x, batch_size=1):

/glob/intel-python/python3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1361           initial_epoch=initial_epoch,
   1362           steps_per_epoch=steps_per_epoch,
-> 1363           validation_steps=validation_steps)
   1364 
   1365   def evaluate(self,

/glob/intel-python/python3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py in fit_loop(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    262           ins_batch[i] = ins_batch[i].toarray()
    263 
--> 264         outs = f(ins_batch)
    265         if not isinstance(outs, list):
    266           outs = [outs]

/glob/intel-python/python3/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   2912       self._make_callable(feed_arrays, feed_symbols, symbol_vals, session)
   2913 
-> 2914     fetched = self._callable_fn(*array_vals)
   2915     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   2916     return fetched[:len(self.outputs)]

/glob/intel-python/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1380           ret = tf_session.TF_SessionRunCallable(
   1381               self._session._session, self._handle, args, status,
-> 1382               run_metadata_ptr)
   1383         if run_metadata:
   1384           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/glob/intel-python/python3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: slice index 1 of dimension 0 out of bounds.
	 [[Node: loss/intent_slot_crf_loss/cond/strided_slice_4 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss/intent_slot_crf_loss/cond/Shape_4, metrics/accuracy/cond/rnn_1/strided_slice_2/stack, metrics/accuracy/cond/rnn_1/strided_slice_2/stack_1, metrics/accuracy/cond/rnn_1/strided_slice_2/stack)]]

Looks code is broken in v0.3, please let me know the solution for the above issue.

**Comment by peteriz** [comment]
Fixed
