### ISSUE TITLE
Not able to install nlp_architect v0.2

### ISSUE THREAD

**Issue by RajeswariPonnuru** [NervanaSystems/nlp-architect#21]
#### Target objective:
nlp_architect v0.2 installation using pip
#### Steps to objective:
$ **pip install nlp-architect==0.2.1**
Collecting nlp-architect==0.2.1
  Could not find a version that satisfies the requirement nlp-architect==0.2.1 (from versions: 0.3.1)
No matching distribution found for nlp-architect==0.2.1
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 
Tried with v0.2.1, 0.2, v0.2 and different combinations.

Since v0.3 has issues in running intent extraction demo, I want to install v0.2 and try.

**Comment by peteriz** [comment]
@RajeswariPonnuru the issue has been fixed and the example is working with NLP Architect 0.3.1
