### ISSUE TITLE
NP semantic segmentation related errors

### ISSUE THREAD

**Issue by nayanleo** [NervanaSystems/nlp-architect#22]
#### Target objective:
I am trying to run the script data.py from np_semantic_segmentation and gettinng the error that is cannot allocate the memory.

#### Steps to objective:
step 1: 
follows the command : python data.py --data input_data_path.csv --output output_prepared_path.csv --w2v_path <path_to_w2v>/GoogleNews-vectors-negative300.bin.gz
 
step 2 : 
on the terminal i get 
start loading wordvec model
.
.
.
finish loading feature extraction services.
. .  . .
and the getting error such as 

**file "data.py ", line 354
prepare_data(data_path, output_path, word2vec_path, http_proxy, https_proxy)

 file "data.py ", line 168, in prepare_data
p = Pool(10)

self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory**

My system configuration is : 
Dell Inspiron, 
memory : 3.8 GiB
processor : Intel® Core™ i5-5200U CPU @ 2.20GHz × 4 
OS type : 64-bit
Disk : 980.2 GB

 Kindly address my problem, and give me suggestions, 
Thanking You,
Nayan choudhari.

**Comment by peteriz** [comment]
Hi @nayanleo, this looks like your machine doesn't have enough memory to launch 10 processes. (looking at the specs you have ~4GB RAM). 
I can suggest that you either try reducing the number of processes - for example, `p = Pool(2)`
or
removing the sub-process loop and running the feature extraction linearly; call `build_feature_vector` for each element in `np_list`
or
 try running the example/algorithm on a machine with more memory

**Comment by nayanleo** [comment]
> Hi @nayanleo, this looks like your machine doesn't have enough memory to launch 10 processes. (looking at the specs you have ~4GB RAM).
> I can suggest that you either try reducing the number of processes - for example, `p = Pool(2)`
> or
> removing the sub-process loop and running the feature extraction linearly; call `build_feature_vector` for each element in `np_list`
> or
> try running the example/algorithm on a machine with more memory

thank you mr. @peteriz for response. i will do  whatever you have suggested and will give feedback on it soon.
