### ISSUE TITLE
Problems with model loading in intent extraction

### ISSUE THREAD

**Issue by ygk09** [NervanaSystems/nlp-architect#24]
#### Target objective:
After I have run [train_mlt_model.py] according to the Readme.md, a model can be obtained. Save this model by 'model.save' method and reload it as model1. Then the prediction on the validation data of these two models are different.
#### Steps to objective:
- Run [train_mlt_model.py] and a model is obtained. This model is stored in the memory.
- Save this model on the disk by command: model.save(model_path)
- Reload this model from the disk by command: 
   model1 = MultiTaskIntentModel(); 
   model1.load(model_path)
- Use the commands below to evaluate these two model:
    predictions = model.predict(test_inputs, batch_size=args.b)
    eval = get_conll_scores(predictions, test_y,
                            {v: k for k, v in dataset.tags_vocab.vocab.items()})
    print(eval)

    predictions = model1.predict(test_inputs, batch_size=args.b)
    eval = get_conll_scores(predictions, test_y,
                            {v: k for k, v in dataset.tags_vocab.vocab.items()})
    print(eval)
- The results are different:
 model: avg / total      0.820     0.833     0.821      1794
 model1:avg / total      0.817     0.826     0.814      1794

So, why the predictions of model and model1 are different ?

**Comment by peteriz** [comment]
I followed your description and did not succeed in replicating your bug.
Care you share more info?

**Comment by ygk09** [comment]
OK. Belows are my procedures:
1. In PyCharm, run [train_mlt_model.py] in python console mode. 
2. After 5 epochs, the trained model can be obtained in the memory. It is saved on the disk with a name 'model.h5'. Meanwhile, test_inputs and test_y are also stored in the memory.
3. In the python console, input command:
     model1=MultiTaskIntentModel()
    and command:
     model1.load('model1.h5')
    Then we can get two models in the memory: model and model1. The former is obtained after 5 epochs training. The latter is obtained by loading a file, which is obtained through saving the former on the disk. 
4. In the python console, input command:
    predictions = model.predict(test_inputs, batch_size=args.b)
    eval = get_conll_scores(predictions, test_y,
                                          {v: k for k, v in dataset.tags_vocab.vocab.items()})
    print(eval)
and then input:
    predictions = model1.predict(test_inputs, batch_size=args.b)
    eval = get_conll_scores(predictions, test_y,
                                          {v: k for k, v in dataset.tags_vocab.vocab.items()})
    print(eval)
5. The results of 'print(eval)' are very differnt.
By the way, the parameter 'use_cudnn' is set to be 'True'.

**Comment by peteriz** [comment]
I got it.
The issue is a mismatch when training a model using  cudnn LSTM cells and then loading into CPU LSTM cells (there are reports of this issue with Tensorflow). 
I will work on a fix so this would be possible, until then please use a single backend for train/inference.
Thanks!
