### ISSUE TITLE
How to use MLP classifier on multi-context features ?

### ISSUE THREAD

**Issue by hanayashiki** [NervanaSystems/nlp-architect#36]
Hello, I read your published paper "Term Set Expansion based NLP Architect by Intel AI Lab" and am quite impressed by your multi-context-based method. However, I found that the code associated with your methods in the repository seems not to implement this method. In your paper, you mentioned that 
```
we train a Multilayer Perceptron
(MLP) classifier that predicts whether a candidate
term should be part of the expanded set based on
ten similarity scores (considered as input features)
obtained by the five different context types and
two different similarity-scoring methods
```
but in the code `https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/solutions/set_expansion/set_expand.py`, according to my understanding, you used another simpler method based on the similarity between a single embedding of seeds and candidates, and I cannot find the implementation of your algorithm in the paper.
Is there any code in the repository to use your algorithm in the paper? Thank you.

**Comment by jmamou** [comment]
Hello,
Thanks for your comment!
The full implementation of the multi-context term embeddings approach will be included in the NLP architect in the coming months.

**Comment by hanayashiki** [comment]
@jmamou Thank you for your reply. I am really looking forward to your code!
