### ISSUE TITLE
ner example trows ImportError

### ISSUE THREAD

**Issue by yoptar** [NervanaSystems/nlp-architect#4]
#### Target objective:
I would be great if `ner` example would not trow an `ImportError: cannot import name 'saving'` error that happens because of broken `keras-contrib` package.
#### Steps to objective:
- modify requirements.txt to reference a specific working commit of `keras-contrib` package

#### Pull-Request related:
#3 could do it

**Comment by yinyinl** [comment]
Thanks for reporting the issue and the PR. We will add your fix soon.

**Comment by frankTian92** [comment]
I have met the same error, is it fixed already?

**Comment by peteriz** [comment]
This issue was fixed in release 0.2.
