### ISSUE TITLE
Question about Seq2SeqIntentModel

### ISSUE THREAD

**Issue by hkvision** [NervanaSystems/nlp-architect#40]
This is used for slot tagging, and in the example you provide, the dataset is SNIPS and it is used for NER. Wondering why it is placed under intent_extraction and come with the name IntentModel?

**Comment by peteriz** [comment]
The SNIPS NLU benchmark can be used as an intent dataset since it contains annotations of _intent type_ and _entities_ for each intent type.

**Comment by hkvision** [comment]
So my question is that if I use another dataset with entities only, can I use Seq2SeqIntentModel?

**Comment by peteriz** [comment]
It is possible, but you will still have to provide _intent_ labels as the model expects to see 2 annotations (outputs). You can mark the label of the _intent_ the same label for all samples and the network should learn it pretty quickly.
Another options would be to replicate the model (own your own) without the intent prediction part of the network.

**Comment by hkvision** [comment]
But in the model definition here: https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/models/intent_extraction.py#L337 , there is only one output, namely tags, and also in your SNIPS example here: https://github.com/NervanaSystems/nlp-architect/blob/master/examples/intent_extraction/train_seq2seq_model.py#L83 , train_i is never used. Thus I suppose intent is not needed at all?
I understand that for the MultiTaskIntentModel if I only have entities, I can follow your way to use the model. I'm asking about the Seq2SeqIntentModel.

**Comment by peteriz** [comment]
You are correct. `Seq2SeqIntentModel` model only tags for intent slots (entities).
