### ISSUE TITLE
word_lstm_dims is not used in NERCRF

### ISSUE THREAD

**Issue by hkvision** [NervanaSystems/nlp-architect#41]
https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/models/ner_crf.py#L45
Seems that the argument `word_lstm_dims` is never used in the model. Is the model missing this argument or this is a useless argument?

**Comment by peteriz** [comment]
@hkvision , please ignore, I'm going to push an updated CRF layer shortly.

**Comment by peteriz** [comment]
Updated in v0.4
