### ISSUE TITLE
Question: What does None mean in NER?

### ISSUE THREAD

**Issue by hkvision** [NervanaSystems/nlp-architect#42]
https://github.com/NervanaSystems/nlp-architect/blob/master/examples/ner/interactive.py#L88
Wondering if the NER result of a word is [1 0 0 ... all 0's] and the corresponding tag ought be of label 0. But tag_vocab keys starts from 1 and during inference, `y_vocab.get(n, None)` None is assigned to it. I'm not sure what None means, namely what entity shall I treat for this word? as UNKNOWN?

**Comment by peteriz** [comment]
its just a default value for querying the tag vocab (for safe printing)
