### ISSUE TITLE
Error running absa train.py example

### ISSUE THREAD

**Issue by hsm207** [NervanaSystems/nlp-architect#44]
I am able to successfully install nlp architect but I get an error when i try to run:

`python nlp-architect/examples/absa/train/train.py`

The error I get is:

![image](https://user-images.githubusercontent.com/2398765/56876507-6e43c400-6a7a-11e9-8c1b-e7dfeb52b771.png)

Is there something wrong with the provided dataset?

I am using the following python version:

```
3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0]
```

**Comment by danielkorat** [comment]
Hi,

Thanks for noticing this issue, we are already working on a small patch which fixes it. The probable reason is system-dependant encoding formats. Meanwhile, please try adding the argument `encoding='utf-8'` to the `open()` command at `models/absa/utils.py` line 201. This should solve it. You can do the same in other relevant `open()` calls if this issue comes up. 
BTW, which OS are you using? 

Thanks

**Comment by hsm207** [comment]
Hi @danielkorat,

Thanks for the tip.

I couldn't figure out what to change to fix this error:

![image](https://user-images.githubusercontent.com/2398765/56901071-da014d80-6ac9-11e9-8a0f-78d639ffc753.png)

Any advice?

I'm actually running nlp architect inside a docker container. Its's based off the tensorflow 1.12 container so it should be ubuntu 16.04. Here's the dockerfile:

```
FROM tensorflow/tensorflow:1.12.0-gpu-py3

# installation instructions from http://nlp_architect.nervanasys.com/installation.html

RUN apt-get update && apt-get install -y \
    git \
    libhdf5-dev \
    pkg-config \
    wget

WORKDIR /tmp

# use Anaconda instead of virtualenv to manage virtual environments
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda && \
    rm miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN /opt/conda/bin/conda create -y -n nlp-architect setuptools wheel python=3.6

WORKDIR /opt

RUN export NLP_ARCHITECT_BE=GPU && \
    git clone https://github.com/NervanaSystems/nlp-architect.git && \
    cd nlp-architect && \
    # since it is not recommended to have build time GPU support, we will modify requirements.txt to explicitly install
    # tensorflow-gpu.
    # see: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#can-i-use-the-gpu-during-a-container-build-ie-docker-build
    sed -i 's/tensorflow==/tensorflow-gpu==/' requirements.txt && \
    /opt/conda/envs/nlp-architect/bin/pip install -e .
```

**Comment by danielkorat** [comment]
Hi @hsm207,

Please try running this shell command to set default encoding to utf-8: `export PYTHONIOENCODING=utf8`. This should solve all encoding errors altogether. 
If not, see this thread for additional solutions:
https://stackoverflow.com/questions/47968578/python3-utf-8-decode-issue

**Comment by hsm207** [comment]
Hi @danielkorat 

Thanks for the hint.

I finally found the solution here:
https://stackoverflow.com/questions/27931668/encoding-problems-when-running-an-app-in-docker-python-java-ruby-with-u
