### ISSUE TITLE
BISTModel error while loading the pretrained model

### ISSUE THREAD

**Issue by LivingScripts** [NervanaSystems/nlp-architect#49]
I have downloaded the pretrained BIST model but it is not loading when I use the BISTModel.load() function.

What I'm doing is:

`from nlp_architect.models.bist_parser import BISTModel`
`parser = BISTModel()`
`parser.load('/home/zeus/nlp-architect/cache/bist-pretrained/bist.model')`

It gives the following error:

`[dynet] random seed: 1090240239`
`[dynet] allocating memory: 512MB`
`[dynet] memory allocation done.`
`Traceback (most recent call last):`
`File "/home/zeus/Assistance/be/ServiceDispatcher/buildDependencies.py", line 5, in <module>`
    `parser.load(''.__setattr__('parent','/home/zeus/nlp-architect/cache/bist-pretrained/bist.model'))`
`AttributeError: 'str' object has no attribute 'parent'`

`

**Comment by danielkorat** [comment]
Hi,

Thanks for your comment. The `load()` method accepts a `pathlib.Path` object.
Please use it like so:
`from pathlib import Path `
`parser.load("path/to/model.json")`
We will update the documentation to reflect this requirement.

Thank You
