### ISSUE TITLE
Question: Is anyone using Intel Python with NLP Architect

### ISSUE THREAD

**Issue by javaspaces** [NervanaSystems/nlp-architect#55]
I want to make sure that I can get the results that everyone else is getting with NLP Architect, and I'm curious if anyone using Intel Python. 

I see that Intel Python is NOT in the installation instructions for NLP Architect, and I also see that Intel Python downgrades at least 30 packages during it's installation on Ubuntu 16.04 LTS.

The process that I'm using to install Intel Python is:

`conda install -c intel intelpython3_full`

**Comment by peteriz** [comment]
We haven't integrated conda packaging into NLP Architect but this is more than welcome!

Can you share what are you doing after creating the env with Intel Python? you're just following the installation instructions?

If you have an installation recipe for conda please consider contributing it, thanks!

**Comment by javaspaces** [comment]
Yes, I'll be sharing alot very soon. I'm going to try to ping you directly about what I'm working on with other Intel folks
