### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by peteriz** [NervanaSystems/nlp-architect#57]
#### Target objective:
Add docker image

**Comment by Wittionary** [comment]
Hey @peteriz , I'd like to help with this. As someone who would be coming into this project completely new, any basics I should get familiar with or hurdles you can foresee?

**Comment by peteriz** [comment]
Hi @Wittionary, the idea is to create a simple dockerfile that contains python 3.6 and nlp-architect installed properly (cpu or gpu).
In addition, expose a port with the demo running (see `nlp_architect server` command that launches a small UI with our 4 pre-trained models) so that it could be fired-up easily with Docker.

Thanks!

**Comment by jacobkdick** [comment]
@peteriz Why was this closed? Could you include an explanation?

**Comment by peteriz** [comment]
@jacobkdick we've added a Dockerfile with the release last week.
