### ISSUE TITLE
Validate python version

### ISSUE THREAD

**Issue by peteriz** [NervanaSystems/nlp-architect#61]
#### Target objective:
validate supported python in the library usage.
related to error in #60

**Comment by SamujjwalSam** [comment]
Hi, Is anyone working on this? Otherwise I would love to work on validating Python version.

**Comment by peteriz** [comment]
Hi, not sure how this would be implemented.
Maybe a static check when running the CLI?
I've already added python 3.6+ in the setup.py file.
