### ISSUE TITLE
Intent Extraction: 'GetWeather' intent: Web viewer ignores to show the annotation/label for "timeRange"

### ISSUE THREAD

**Issue by javaspaces** [NervanaSystems/nlp-architect#65]
#### Target objective:
I'm using the intent extraction demo with the pre-trained model that is downloaded when you start the embedded server. This is my example sentence:
"What's the forecast for today in Chicago?"

Below is the annotated result:

```
{'model_name': 'intent_extraction', 'docs': [{'id': 1, 'doc': "What's the forecast for today in Chicago?"}]}
Detected intent type: GetWeather
What	O	
's	O	
the	O	
forecast	O	
for	O	
today	B-timeRange	
in	O	
Chicago	B-city	
?	O	
```
As you can see, "today" is correctly annotated (in the terminal and in the JSON response) as a timeRange. The problem is that the visualizer on the web view only shows the annotation for the city. The timeRange is not visualized with its annotation.

#### Pull-Request related:
nlp_architect v. 0.4 Post 2

**Comment by peteriz** [comment]
Thanks for reporting. We will verify this issue.
