### ISSUE TITLE
please provide me a link for ABSApp User Interface.

### ISSUE THREAD

**Issue by akpanda734386** [NervanaSystems/nlp-architect#66]
#### Steps to objective:
- [ ]
- [ ]

**Comment by danielkorat** [comment]
Hi, 
Thanks for your interest in ABSApp. 
The UI is in final stages of release, and will be available in the next version release, expected in the first weeks of August.

**Comment by danielkorat** [comment]
Hi @akpanda734386 ,
The code for ABSApp UI was released. You can launch it by executing this module:
https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/solutions/absa_solution/ui.py
