### ISSUE TITLE
How does it support Chinese?

### ISSUE THREAD

**Issue by fallcat** [NervanaSystems/nlp-architect#7]
I saw in the paper for BIST that it works well in both Chinese and English, but didn't find how to use Chinese model in any of the functionalities. Does it come with a Chinese model? Or do we have to train our own?

**Comment by danielkorat** [comment]
A Chinese model is not provided in this distribution, but you can train it yourself of course.

**Comment by fallcat** [comment]
Is Chinese model provided in functionalities other than BIST? How about other languages?

**Comment by yinyinl** [comment]
We don't have a planned date to add feature such as Chinese tokenizer yet, but we welcome any inputs or contributions to the code base.
