### ISSUE TITLE
Any readme for BERT example?

### ISSUE THREAD

**Issue by hkvision** [NervanaSystems/nlp-architect#79]
#### Target objective:
Want help to run https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/procedures/transformers/glue.py

Hi, I want to run the bert example newly added to the repo. Wondering is there any readme for running the example or any documentation for bert/quantized-bert related features?
For instance, where to download model and 'labels.txt'?

Thanks so much for your help in advance!

**Comment by peteriz** [comment]
Hi @hkvision,
We'll be publishing new documentation in the coming days.

**Comment by peteriz** [comment]
for GLUE tasks, we're using the published GLUE benchmark data (1 directory for each task)
and for models using `TokenClsProcessor` we're using tab separated data files (e.g. conll2000/2003 style files) with train/test/dev and labels.txt containing the list of labels of the data set.

**Comment by hkvision** [comment]
Hi @peteriz Thanks for your really quick reply!
Look forward to the new documentations :).
I have downloaded GLUE dataset. But wondering why in the code, `labels.txt` is under `model_path`: https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/models/transformers/base_model.py#L196 ?

**Comment by peteriz** [comment]
labels.txt is created once you save the model, otherwise our model example with GLUE tasks loads the labels that are encoded in GLUE's data loader

**Comment by hkvision** [comment]
Oh, thank. My bad. By default the example is running inference and needs label file. Now I can run the training successfully. Thanks for your help @peteriz and look forward to more documentations about bert!

**Comment by peteriz** [comment]
Hi @hkvision. New documentation and code is up.
If you have any feedback we'd be glad to hear.

**Comment by hkvision** [comment]
> Hi @hkvision. New documentation and code is up.
> If you have any feedback we'd be glad to hear.

Sure. Thank you so much!
