### ISSUE TITLE
intent extraction interactive mode results are totally incorrect while testing with train data

### ISSUE THREAD

**Issue by minsuk-heo** [NervanaSystems/nlp-architect#8]
#### Target objective:
interactive mode should predicts well on sentences from train data or validation data
#### Steps to objective:
- python train_joint_model.py --model_path model_v1.h5 --dataset_path ~/git/nlu-benchmark/2017-06-custom-intent-engines
- python interactive.py --model_path model_v1.h5 --dataset_path ~/git/nlu-benchmark/2017-06-custom-intent-engines
- input: Weather next year in Dominica
- expected result: intent as GetWeather
- actual result: PlayMusic

the model final performance from training was below,
intent_classifier_loss: 0.0617 - slot_tag_classifier_loss: 0.0473 - intent_classifier_categorical_accuracy: 0.9805 - slot_tag_classifier_categorical_accuracy: 0.9861 - val_loss: 0.1243 - val_intent_classifier_loss: 0.0677 - val_slot_tag_classifier_loss: 0.0566 - val_intent_classifier_categorical_accuracy: 0.9771 - val_slot_tag_classifier_categorical_accuracy: 0.9845

**Comment by yinyinl** [comment]
Thanks for reporting the issues @minsuk-heo. @peteriz is able to reproduce and fix the issue. we will push a patch soon.

**Comment by peteriz** [comment]
This issue was fixed in release 0.2. Thanks for reporting the bug!
