### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by saareliad** [NervanaSystems/nlp-architect#82]
#### Target objective:
Error while installing from source.
> `ERROR: wordfreq 2.2.1 has requirement regex<=2018.02.21,>=2017.07.11, but you'll have regex 2019.6.8 which is incompatible.`

#### Steps to objective:
1. Followed installation instructions from [nlp-architect](https://github.com/NervanaSystems/nlp-architect):
```
%cd ~/workspace/
!git clone https://github.com/NervanaSystems/nlp-architect.git
%cd nlp-architect
!pip install -e .
```
got the following error:
> `ERROR: wordfreq 2.2.1 has requirement regex<=2018.02.21,>=2017.07.11, but you'll have regex 2019.6.8 which is incompatible.`

2. Tried a second time:
with conda from source, as suggested here:
#https://github.com/NervanaSystems/nlp-architect/issues/63

```
pip install --upgrade pip
conda create -n intelnlp python=3.6
conda activate intelnlp

git clone https://github.com/NervanaSystems/nlp-architect.git
cd nlp-architect
export NLP_ARCHITECT_BE=GPU # choices are CPU | GPU | MKL
pip install -e . 
```
> `ERROR: wordfreq 2.2.1 has requirement regex<=2018.02.21,>=2017.07.11, but you'll have regex 2019.6.8 which is incompatible.`

**Comment by hkvision** [comment]
I also met the same problem. I just manually install `regex==2018.02.21` and it works.

**Comment by peteriz** [comment]
I fixed this in `requirements.txt`
