### ISSUE TITLE
question: How to run transformers in an IDE?

### ISSUE THREAD

**Issue by hkvision** [NervanaSystems/nlp-architect#85]
Hi,

I found that you have unified the running procedure using `register_cmd`, and uses `nlp_architect train transformer_glue` for example to run training in glue.py.

Want to ask in this case how can I run in an IDE? As normally when running python scripts, the command would be `python glue.py ...`.

Thanks so much for your help in advance!

**Comment by peteriz** [comment]
you can run the `nlp_architect/nlp_architect` command (or script) with required arguments to launch a train/run session.
I'm not sure what kind of IDE you're using but you can set up a run configuration with the above command and add the arguments of `train transformer_glue` and any other arguments per model.

**Comment by hkvision** [comment]
Thanks so much for your help! I have successfully run it in PyCharm.
