### ISSUE TITLE
Errors appears in intent extraction

### ISSUE THREAD

**Issue by frankTian92** [NervanaSystems/nlp-architect#9]
There is the same error as NER in intent extraction for joint model: ImportError: cannot import name 'saving'

**Comment by peteriz** [comment]
Thanks for reporting. We fixed the issue and will publish a new version soon.

**Comment by peteriz** [comment]
This issue was fixed in release 0.2.

**Comment by frankTian92** [comment]
Received，what could I do？



可用于iOS的myMail发送


2018年8月15日 星期三 +0800 23:07 发件人 notifications@github.com  <notifications@github.com>:
