### ISSUE TITLE
question: About QuantizedBert Performance

### ISSUE THREAD

**Issue by hkvision** [NervanaSystems/nlp-architect#90]
Hi, I have both trained `TransformerSequenceClassifier` for bert and bert_quant.
But when I calculate the inference time, I find quant_bert is much slower than bert (290s vs 170s). And I'm using an ordinary developer machine.
I saw the discussion here #86 and know that the quantization process is not kernel optimized, but it is still strange that I get such performance result.
Am I doing something wrong? I have debugged that `classifier.model` is correct and for quantized bert it goes into the quantized forward...

Hope to have some suggestions or guidance! Thanks so much in advance!

**Comment by ofirzaf** [comment]
Hi,
Since the quantization is happening in real time you see degradation in performance using the quantized model, meaning that on top of the regular BERT operations you have the quantization operations. Since the graph of the quantized model has more operations it is slower.

**Comment by hkvision** [comment]
Hi @ofirzaf Thanks so much for your quick reply.
But wouldn't the regular BERT operations be faster? Or this is because the overhead of quantization process is even larger than the gain?
Then in this case, what is the benefit of using a quantized model? Thanks.

**Comment by ofirzaf** [comment]
There is no gain performance wise from quantization in our model, we published this model in order to show that it is possible to quantize BERT to 8bit without accuracy loss and how to do it.
In order to see performance gain from the quantized model you need to export the model in 8bit format and make use of optimized kernels which use dedicated hardware for quantized GEMM operations.

**Comment by hkvision** [comment]
Thanks for your clarification @ofirzaf . I'm looking into the code for more details. I leave this issue open here in case we may consider performance in the future.
